#!/bin/bash

echo "🎨 StreamStyle AI - Quick Commands"
echo "=================================="
echo ""

# Check if in correct directory
if [ ! -f "start.sh" ]; then
    echo "❌ Error: Run this from streamstyle-ai/ directory"
    exit 1
fi

echo "📋 Available Commands:"
echo ""
echo "1. Start Everything (Recommended)"
echo "   ./start.sh"
echo ""
echo "2. Backend Only"
echo "   cd backend && source venv/bin/activate && python main.py"
echo ""
echo "3. Frontend Only"
echo "   cd frontend && npm run dev"
echo ""
echo "4. Check Backend Status"
echo "   curl http://localhost:8000"
echo ""
echo "5. Check GPU Available"
echo "   python -c 'import torch; print(torch.cuda.is_available())'"
echo ""
echo "6. Install Dependencies"
echo "   cd backend && pip install -r requirements.txt"
echo "   cd frontend && npm install"
echo ""
echo "7. Clean Cache (if issues)"
echo "   rm -rf backend/__pycache__"
echo "   rm -rf frontend/node_modules/.vite"
echo ""
echo "8. View Logs"
echo "   # Backend logs appear in terminal"
echo "   # Frontend logs in browser console (F12)"
echo ""
echo "📡 URLs:"
echo "   Frontend: http://localhost:3000"
echo "   Backend:  http://localhost:8000"
echo "   API Docs: http://localhost:8000/docs"
echo ""
echo "🎤 Voice Commands:"
echo "   Say: 'anime', 'cyberpunk', 'watercolor', 'pixel art'"
echo "   Say: 'van gogh', 'oil painting', 'sketch', 'pop art'"
echo ""
echo "⚡ Performance Tips:"
echo "   - GPU: 0.3-0.8s per frame"
echo "   - CPU: 2-5s per frame"
echo "   - Lower resolution = faster (edit backend/main.py line 52)"
echo "   - Increase interval = smoother (edit frontend/src/App.jsx line 95)"
echo ""
echo "🐛 Troubleshooting:"
echo "   - Port 8000 in use: kill -9 \$(lsof -ti:8000)"
echo "   - Port 3000 in use: kill -9 \$(lsof -ti:3000)"
echo "   - Model download slow: export HF_HOME=/tmp/huggingface"
echo "   - WebSocket error: Check backend is running"
echo ""
echo "📚 Documentation:"
echo "   - README.md - Full guide"
echo "   - docs/ARCHITECTURE.md - System design"
echo "   - docs/ANT_MEDIA_INTEGRATION.md - Broadcasting"
echo "   - docs/DEMO_SCRIPT.md - Presentation guide"
echo ""
